### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by jefersondaniel** [andersondanilo/password_storage#1]
I am using Chrome 40.0.2209.0 dev (64-bit) and get the following error:

authService.js:94 Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
ionic.bundle.js:8762 Uncaught Error: [$injector:unpr] Unknown provider: authServiceProvider <- authService
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=authServiceProvider%20%3C-%20authService

**Comment by andersondanilo** [comment]
Hey Hey Jeferson,

Strict mode was removed due unexpected errors.

Please, clean your cache and  try again.
